parameters:
#    xidea_inventory.example.class: Xidea\Bundle\InventoryBundle\Example

services:
#    xidea_inventory.example:
#        class: %xidea_inventory.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
